
RideID: ride["Ride ID"],
Ride_Status: ride["Status"],
Ride_Date: ride["Ride Date"],
Customer_FirstName: ride["First Name"],
Customer_LastName: ride["Last Name"],
Phone_Number: ride["Phone"],
Transportation_Type: ride["Transportation Type"],
Cancel_Reason: ride["Cancel Reason"],
Cost: ride["Cost"],
Pick_Up_Time: ride["Pick Up Time"],
Arrival_Time: ride["Arrival Time"],
Estimated_Arrival_Time: ride["Estimated Arrival Time"],
Scheduled_Pickup_Time: ride["Scheduled Pickup Time"],
Estimated_Distance: ride["Estimated Distance"],
Pickup_Address: ride["Pickup Address"],
Pickup_Lat: ride["Pickup Lat"],
Pickup_Lng: ride["Pickup Lng"],
Pickup_Directions: ride["Pickup Directions"],
Dropoff_Address: ride["Dropoff Address"],
Dropoff_Lat: ride["Dropoff Lat"],
Dropoff_Lng: ride["Dropoff Lng"],
Dropoff_Directions: ride["Dropoff Directions"],
Driver_FirstName: ride["Driver First Name"],
Driver_Photo_Url: ride["Driver Photo Url"],
Driver_Phone: ride["Driver Phone"],
Vehicle_Color: ride["Vehicle Color"],
Vehicle_Make: ride["Vehicle Make"],
Vehicle_Model: ride["Vehicle Model"],
Vehicle_License: ride["Vehicle License"],
Vehicle_Photo_Url: ride["Vehicle Photo Url"],
Provider_Name: ride["Provider Name"],
Provider_Trip_Id: ride["Provider Trip Id"],
Rider_Patient_ID: ride["Rider/Patient ID"],
Member_ID: ride["Member ID"],

//jumbledData

"Ride ID": "2470242",
  "Status": "PENDING_UPDATE",
  "Ride Date": "12/14/2023",
  "First Name": "JAMIE",
  "Last Name": "SHIELDS",
  "Phone": "46",
  "Transportation Type": "3205223498",
  "Cancel Reason": "NON_RIDESHARE_SEDAN",
  "Cost": "NONE",
  "Pick Up Time": "",
  "Arrival Time": "12/14/2023 07:15 AM (CST)",
  "Estimated Arrival Time": "12/14/2023 07:45 AM (CST)",
  "Scheduled Pickup Time": "12/14/2023 07:45 AM (CST)",
  "Estimated Distance": "12/14/2023 07:15 AM (CST)",
  "Pickup Address": "12.2939",
  "Pickup Lat": "215 3rd St SW, Renville, MN 56284, USA",
  "Pickup Lng": "44.7875545",
  "Pickup Directions": "-95.2148623",
  "Dropoff Address": "Please call upon arrival",
  "Dropoff Lat": "100 Healthy Way, Olivia, MN 56277, USA",
  "Dropoff Lng": "44.7744069",
  "Dropoff Directions": "-94.972512",
  "Driver First Name": "",
  "Driver Photo Url": "",
  "Driver Phone": "",
  "Vehicle Color": "",
  "Vehicle Make": "",
  "Vehicle Model": "",
  "Vehicle License": "",
  "Vehicle Photo Url": "",
  "Provider Name": "",
  "Provider Trip Id": "West Central Transportation",
  "Rider/Patient ID": "885-2470242",
  "Member ID": "1774909",
  "": "2843425",
              



RideID: ride["Ride ID"],
                  Ride_Status: ride["Status"],
                  Ride_Date: ride["Ride Date"],
                  Customer_FirstName: ride["First Name"],
                  Customer_LastName: ride["Last Name"],
                  Phone_Number: ride["Transportation Type"],
                  Transportation_Type: ride["Cancel Reason"],
                  Cancel_Reason: ride["Cost"],
                  Cost: ride["Pick Up Time"],
                  Pick_Up_Time: ride["Arrival Time"],
                  Arrival_Time: ride["Estimated Arrival Time"],
                  Estimated_Arrival_Time: ride["Scheduled Pickup Time"],
                  Scheduled_Pickup_Time: ride["Estimated Distance"],
                  Estimated_Distance: ride["Pickup Address"],
                  Pickup_Address: ride["Pickup Lat"],
                  Pickup_Lat: ride["Pickup Lng"],
                  Pickup_Lng: ride["Pickup Directions"],
                  Pickup_Directions: ride["Dropoff Address"],
                  Dropoff_Address: ride["Dropoff Lat"],
                  Dropoff_Lat: ride["Dropoff Lng"],
                  Dropoff_Lng: ride["Dropoff Directions"],
                  Dropoff_Directions: ride["Driver First Name"],
                  Driver_FirstName: ride["Driver Photo Url"],
                  Driver_Photo_Url: ride["Driver Phone"],
                  Driver_Phone: ride["Vehicle Color"],
                  Vehicle_Color: ride["Vehicle Make"],
                  Vehicle_Make: ride["Vehicle Model"],
                  Vehicle_Model: ride["Vehicle License"],
                  Vehicle_License: ride["Vehicle Photo Url"],
                  Vehicle_Photo_Url: ride["Provider Name"],
                  Provider_Name: ride["Provider Trip Id"],
                  Provider_Trip_Id: ride["Rider/Patient ID"],
                  Rider_Patient_ID: ride["Member ID"],
                  Member_ID: ride[""],

                  select:{
          RideID:true,
          Ride_Status:true,
          Ride_Date:true,
          Customer_FirstName:true,
          Customer_LastName:true,
          Phone_Number:true,
          Transportation_Type:true,
          Pick_Up_Time:true,
          Arrival_Time:true,
          Estimated_Distance:true,
          Pickup_Address:true,
          Dropoff_Address:true,
          Pickup_Directions:true
        }