
RideID: ride["Ride ID"],
Ride_Status: ride["Status"],
Ride_Date: ride["Ride Date"],
Customer_FirstName: ride["First Name"],
Customer_LastName: ride["Last Name"],
Phone_Number: ride["Phone"],
Transportation_Type: ride["Transportation Type"],
Cancel_Reason: ride["Cancel Reason"],
Cost: ride["Cost"],
Pick_Up_Time: ride["Pick Up Time"],
Arrival_Time: ride["Arrival Time"],
Estimated_Arrival_Time: ride["Estimated Arrival Time"],
Scheduled_Pickup_Time: ride["Scheduled Pickup Time"],
Estimated_Distance: ride["Estimated Distance"],
Pickup_Address: ride["Pickup Address"],
Pickup_Lat: ride["Pickup Lat"],
Pickup_Lng: ride["Pickup Lng"],
Pickup_Directions: ride["Pickup Directions"],
Dropoff_Address: ride["Dropoff Address"],
Dropoff_Lat: ride["Dropoff Lat"],
Dropoff_Lng: ride["Dropoff Lng"],
Dropoff_Directions: ride["Dropoff Directions"],
Driver_FirstName: ride["Driver First Name"],
Driver_Photo_Url: ride["Driver Photo Url"],
Driver_Phone: ride["Driver Phone"],
Vehicle_Color: ride["Vehicle Color"],
Vehicle_Make: ride["Vehicle Make"],
Vehicle_Model: ride["Vehicle Model"],
Vehicle_License: ride["Vehicle License"],
Vehicle_Photo_Url: ride["Vehicle Photo Url"],
Provider_Name: ride["Provider Name"],
Provider_Trip_Id: ride["Provider Trip Id"],
Rider_Patient_ID: ride["Rider/Patient ID"],
Member_ID: ride["Member ID"],
              