-- AlterTable
ALTER TABLE "CompletedRides" ADD COLUMN     "deadHead" TEXT NOT NULL DEFAULT 'NULL',
ADD COLUMN     "isPaid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "loadType" TEXT NOT NULL DEFAULT 'NULL',
ADD COLUMN     "totalAmount" TEXT NOT NULL DEFAULT 'NULL';

-- AlterTable
ALTER TABLE "Rides" ADD COLUMN     "deadHead" TEXT NOT NULL DEFAULT 'NULL',
ADD COLUMN     "isPaid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "loadType" TEXT NOT NULL DEFAULT 'NULL',
ADD COLUMN     "totalAmount" TEXT NOT NULL DEFAULT 'NULL';
